---
repos:
  - hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
  - hooks:
      - id: black
    repo: https://github.com/psf/black
    rev: 24.10.0
  - hooks:
      - id: pyproject-flake8
    repo: https://github.com/csachs/pyproject-flake8/
    rev: v7.0.0
  - hooks:
      - id: isort
    repo: https://github.com/PyCQA/isort/
    rev: 5.13.2
  - hooks:
      - args: [-c, "pyproject.toml"]
        id: bandit
    repo: https://github.com/PyCQA/bandit/
    rev: 1.7.10
  - hooks:
      - id: autoflake
    repo: https://github.com/PyCQA/autoflake/
    rev: v2.3.1
  - hooks:
      - id: pyupgrade
    repo: https://github.com/asottile/pyupgrade/
    rev: v3.19.0
  - hooks:
      - id: shellcheck
    repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
  - hooks:
      - id: mdformat
    repo: https://github.com/executablebooks/mdformat/
    rev: 0.7.19
  - hooks:
      - id: numpydoc-validation
    repo: https://github.com/numpy/numpydoc
    rev: v1.8.0
  - hooks:
      - additional_dependencies: ["types-PyYAML", "types-requests", "types-paramiko"]
        id: mypy
    repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
